### ISSUE TITLE
Support dynamic env config for integration tests

### ISSUE THREAD

**Issue by lizozom** [Outburn-IL/fume-community#10]
Currently, integration tests run with the local config on the machine where they are run.
We want to be able to test several FHIR configurations across different test suites.

* What are the configurations we want to support? (Package versions?)
* How to dynamically load the configurations?

**Comment by lizozom** [comment]
@mechanik-daniel I want to start looking at this.
Can you give me a set of 2-3 few significant `env` that you would wish to run tests against?
Can you explain what would be the impact of changing each env parameter?

Thank you!

**Comment by mechanik-daniel** [comment]
### SERVER_STATELESS
When this is true, there should not be any communication with a FHIR server. No mappings will be loaded to cache on warmup, and functions such as search() and resolve() should return an error. Also no aliases will be loaded since there is no alias resource that can be fetched from the server.
All of the above is still true even if FHIR_SERVER_BASE is set.
When SERVER_STATELESS=false, mappings and aliases should be loaded at warmup from the server set in FHIR_SERVER_BASE. If FHIR_SERVER_BASE is not set when stateless=false it's a misconfiguration. The behaviour can be one of the following:
1. FUME will run in stateless mode, as if SERVER_STATELESS was set to true
2. The default server http://hapi-fhir.outburn.co.il/fhir will be used
Any of the above behaviors is fine since it's not a correct configuration anyway.

### FHIR_SERVER_BASE 
Assuming stateless=false, this will be the FHIR server that mappings and aliases should be loaded from. The list of mappings will be different per FHIR server. The mappings used in the current integration tests exist only on our dev server at [http://ec2-3-124-79-139.eu-central-1.compute.amazonaws.com:52773/csp/healthshare/fume/fhir/r4](http://ec2-3-124-79-139.eu-central-1.compute.amazonaws.com:52773/csp/healthshare/fume/fhir/r4). Changing the server address to our other server [http://hapi-fhir.outburn.co.il/fhir](http://hapi-fhir.outburn.co.il/fhir) (this is also the default server) should make some of the integration test fail (at least as long as we don't load this server with the same data as the dev server).
Another server address that we can use is [http://ec2-3-124-79-139.eu-central-1.compute.amazonaws.com:52773/csp/healthshare/fhirserver/fhir/r4](http://ec2-3-124-79-139.eu-central-1.compute.amazonaws.com:52773/csp/healthshare/fhirserver/fhir/r4) which is the same as the dev server (data-wise), only it requires basic auth, which leads us to the next three env params:

### FHIR_SERVER_AUTH_TYPE, FHIR_SERVER_UN & FHIR_SERVER_PW
This is where we set the user and password for basic auth. If we use the server [http://ec2-3-124-79-139.eu-central-1.compute.amazonaws.com:52773/csp/healthshare/fhirserver/fhir/r4](http://ec2-3-124-79-139.eu-central-1.compute.amazonaws.com:52773/csp/healthshare/fhirserver/fhir/r4) we need to set FHIR_SERVER_AUTH_TYPE=BASIC and the other two, otherwise warmup should fail. If we do set everything correctly - integration tests should pass just like they do when working with the dev server.

### FHIR_VERSION
The first packages that FUME checks for and downloads if missing are the packages of the FHIR version defined here (and their dependencies). So changing this to any other valid version number will lead to the download of different packaes according to
fhirCorePackages param:
```
{
  '4.0.1': 'hl7.fhir.r4.core@4.0.1',
  '4.3.0': 'hl7.fhir.r4b.core@4.3.0',
  '5.0.0': 'hl7.fhir.r5.core@5.0.0'
};
```
A version number that is not one of the above leads to a failed warmup
