### ISSUE TITLE
Improve error msg on coded elements

### ISSUE THREAD

**Issue by nir-r** [Outburn-IL/fume-community#130]
The attached is a valid code for the slices ValueSet but when provided w\o system it raises an error.

The error should point to the lack of system, not a wrong code.

![image](https://github.com/user-attachments/assets/c7e828ad-8b95-4819-ac82-089cd3b29cf6)

```
// FLASH template for ILCore Patient Profile, FHIR version 4.0.1
Instance: undefined // Logical ID for the instance
InstanceOf: http://fhir.health.gov.il/StructureDefinition/il-core-patient

* extension[hmo] // <Extension> 0..1 Extension: Israel Core HMO (קופת חולים)
  // * url = undefined // Fixed value: "http://fhir.health.gov.il/StructureDefinition/ext-il-hmo"
  * value // <CodeableConcept> 0..1 Value of extension
    * coding // <Coding> 0..* Code defined by a terminology system
      // * system = undefined // <uri> 0..1 Identity of the terminology system
      // * version = undefined // <string> 0..1 Version of the system - if relevant
      * code = 101 // <code> 0..1 Symbol in syntax defined by the system
      // * display = undefined // <string> 0..1 Representation defined by the system
      // * userSelected = undefined // <boolean> 0..1 If this coding was chosen directly by the user
    // * text = undefined // <string> 0..1 Plain text representation of the concept
``` 

`Transformation error: Element extension[hmo].value is invalid since none of the codings provided are in the required value set
`

**Comment by mechanik-daniel** [comment]
Since this is a Coding inside a CodeableConcept, and `system` is not mandatory in Coding, and since entries in the Coding array don't all need to match the required ValueSet (because the binding is set on the CodeableConcept), there is no way to know that this code was _intended_ to be a code from the ValueSet and not just an alternative coding _without a system_. Lazy implementations often opt for this to avoid the overhead of managing and assigning URI's to local catalogs. While this is definitely not best practice, it is a valid one. We can't fail the transformation due to not following best practices.

Only when a Coding itself has a required binding **directly** (usually done on slices), AND the ValueSet has a defined system for all codes, it is safe to throw an error on the lack of system. In other cases, including the provided scenario, is is not
