### ISSUE TITLE
Enforce CLA on repo

### ISSUE THREAD

**Issue by lizozom** [Outburn-IL/fume-community#8]
Any contributor to the repo should be prompted to sign a CLA.
If the CLA is not signed, merging the PR back to the Outburn repo should be blocked.

**Comment by lizozom** [comment]
https://cla-assistant.io/

**Comment by lizozom** [comment]
@mechanik-daniel can you please attach the CLA text?

**Comment by mechanik-daniel** [comment]
# Outburn Contributor License Agreement
_Version 1.00, Based on the Apache Contributor License Agreement, available here:  https://apache.org/licenses/icla.pdf_

In order to clarify the intellectual property license granted with Contributions from any person or entity, Outburn Ltd ("Outburn") must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of Outburn; it does not change your rights to use your own Contributions for any other purpose.

By providing Contributions to the Outburn FUME Repository, you accept and agree to the following terms and conditions for Your Contributions (present and future) that you submit to Outburn. Except for the license granted herein to Outburn and recipients of software distributed by it, You reserve all right, title, and interest in and to Your Contributions.

1. **Definitions**. 
   1. "You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with Outburn. For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
   2. "Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to Outburn for inclusion in, or documentation of, any of the products owned or managed by Outburn (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Outburn or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Outburn. for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."
2. **Grant of Copyright License**. Subject to the terms and conditions of this Agreement, You hereby grant to Outburn and to recipients of software distributed by Outburn a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.
3. **Grant of Patent License**. Subject to the terms and conditions of this Agreement, You hereby grant to Outburn and to recipients of software distributed by Outburn a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) was submitted. If any entity institutes patent litigation against You or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that your Contribution, or the Work to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Work shall terminate as of the date such litigation is filed.
4. You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to Outburn, or that your employer has executed a separate CLA with Outburn.
5. You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others). You represent that Your Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.
6. You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 
7. Should You wish to submit work that is not Your original creation, You may submit it to Outburn separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".
8. You agree to notify Outburn of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.

**Comment by mechanik-daniel** [comment]
[CLA.md](https://github.com/Outburn-IL/fume-community/files/14627678/CLA.md)
Here's the text as MD file

**Comment by lizozom** [comment]
@mechanik-daniel I want to make sure this is done using your account so here are the steps to follow:

1. Create a public gist with the CLA content here https://gist.github.com/
2. Create an account with https://cla-assistant.io/ (It's a free, Apache licensed service)
3. Link the `fume-community` to enable the bot 
![image](https://github.com/Outburn-IL/fume-community/assets/3016806/cbfa19a4-0465-40c1-89ae-ba29cc623d6f)
4. The CLA bot will kick in and make sure any contributor's PR has a CLA signature, **before it can be merged**. See an example here https://github.com/Outburn-IL/fume-community/pull/47#issuecomment-2009039561

**Comment by mechanik-daniel** [comment]
1. created gist [https://gist.github.com/mechanik-daniel](url)
2. done
3. linked
4. will check it once I create a pull request

**Comment by lizozom** [comment]
@mechanik-daniel it works
![image](https://github.com/Outburn-IL/fume-community/assets/3016806/5ce9ccb7-3fa2-4439-a8e7-c6a9b9ea9ff3)
